["modules/@zone-eu/wildduck-zonemta-zilter"] # load plugin from node modules
enabled = "receiver"
userName = ""
apiKey = ""
serverHost = ""
zilterUrl = ""              # full zilter url with https
zilterFallbackUrl = ""      # full zilter fallback url with https
logIncomingData = false
subjectMaxLength = 16000
keepAliveTimeout = 5000
keepAliveMaxTimeout = 600e3
maxRetries = 2              # Default to two retries
minRetryTimeout = 100
maxRetryTimeout = 300
timeoutFactor = 1.5
